x-logging:
  &highlight-logging
    driver: fluentd
    options:
      fluentd-address: "tls://otel.highlight.io:24284"
      fluentd-async: "true"
      fluentd-sub-second-precision: "true"
      tag: "highlight.project_id=${HIGHLIGHT_PROJECT_ID}"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    logging: *highlight-logging
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  bot:
    build:
      context: ./
      dockerfile: ./integrations/telegram/Dockerfile
    logging: *highlight-logging
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  caddy:
    image: caddy:2.9-alpine
    restart: unless-stopped
    logging: *highlight-logging
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/caddy:/etc/caddy
      - ~/caddy/caddy_data:/data
      - ~/caddy/caddy_config:/config
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  # Make sure to run init-db.sh before starting the db
  db:
    logging: *highlight-logging
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    volumes:
      - ~/data/getpensive.com/psql:/var/lib/postgresql/
