x-logging:
  &highlight-logging
    driver: fluentd
    options:
      fluentd-address: "tls://otel.highlight.io:24284"
      fluentd-async: "true"
      fluentd-sub-second-precision: "true"
      tag: "highlight.project_id=4d7yjjjd"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    logging: *highlight-logging
    restart: always
    depends_on:
      - db

  # TODO: Update .env file in prod
  # bot:
  #   build:
  #     context: ./
  #     dockerfile: ./integrations/telegram/Dockerfile
  #   logging: *highlight-logging
  #   restart: always
  #   depends_on:
  #     - db

  caddy:
    image: caddy:2.9-alpine
    restart: unless-stopped
    logging: *highlight-logging
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/caddy:/etc/caddy
      - ~/caddy/caddy_data:/data
      - ~/caddy/caddy_config:/config
  
  db:
    logging: *highlight-logging
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ~/data/apps.arashtaher.com/psql:/var/lib/postgresql/data/pgdata
  