services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ~/credentials/env.env:/app/.env:ro
      - ~/credentials/service-account.json:/app/credentials/service-account.json:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  bot:
    build:
      context: ./
      dockerfile: ./integrations/telegram/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  caddy:
    image: caddy:2.9-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/caddy:/etc/caddy
      - ~/caddy/caddy_data:/data
      - ~/caddy/caddy_config:/config
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  # Make sure to run init-db.sh before starting the db
  db:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    volumes:
      - ~/data/getpensive.com/psql:/var/lib/postgresql/
  
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:8000:8000"
