services:
  db:
    ports:
      - 5432:5432 # format here is "port on our machine":"port on container"

  # Adminer provides a nice little web UI to connect to databases
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula # Pick a theme - https://github.com/vrana/adminer/tree/master/designs
    ports:
      - 3333:8080

  # TODO: Bring back after this bug is fixed:
  # https://github.com/tailwindlabs/tailwindcss/issues/15235
  # tailwind:
  #   build:
  #     context: ./tailwind
  #     dockerfile: Dockerfile
  #   tty: true
  #   restart: always
  #   volumes:
  #     - ./tailwind:/tailwind/app/src:ro
  #     - ./templates:/tailwind/app/templates:ro
  #     - ./assets:/app/dst:rw
