services:
  server:
    ports:
      - 8000:8000
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - TTS_SERVICE_URL=http://tts:5000
    depends_on:
      - db
      - tts
    networks:
      - app-network
  
  bot:
    build:
      context: ./
      dockerfile: ./integrations/telegram/Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - DOMAIN=http://server:8000
    depends_on:
      - db
    networks:
      - app-network
