@bookmarkId = fvtnxo5c
@query = search

### Get bookmarks
GET {{host}}/api/v1/bookmarks?page=1
Authorization: Bearer {{token}}

### Get a bookmark
GET {{host}}/api/v1/bookmarks/{{bookmarkId}}
Authorization: Bearer {{token}}

### Create bookmark
POST {{host}}/api/v1/bookmarks
content-type: application/json
Authorization: Bearer {{token}}

{
    // "link": "https://ieeexplore.ieee.org/document/628099"
    "link": "https://stackoverflow.com/questions/75043889/manifest-v3-background-scripts-service-worker-on-firefox"
}

### Search bookmark
GET {{host}}/api/v1/bookmarks/search?query={{query}}
Authorization: Bearer {{token}}

### Delete bookmark
DELETE {{host}}/api/v1/bookmarks/{{bookmarkId}}
Authorization: Bearer {{token}}
