### Get bookmarks
GET {{host}}/api/v1/bookmarks
Authorization: Bearer {{token}}

## Node app

### Get DOM
POST http://localhost:3000/fetch
content-type: application/json

{
    "url": "https://ieeexplore.ieee.org/document/628099"
}

### Search bookmark
GET {{host}}/api/v1/bookmarks/search?query=engineers
Authorization: Bearer {{token}}
