## Node app

### Get DOM
POST http://localhost:3000/fetch
content-type: application/json

{
    // "url": "https://ieeexplore.ieee.org/document/628099"
    "url": "https://stackoverflow.com/questions/75043889/manifest-v3-background-scripts-service-worker-on-firefox"
}
