---
- name: Install git, nginx, and ufw on local machine
  hosts: local
  become: yes
  vars:
    go_version: "1.24"
  roles:
    - go
    - docker
  tasks:
    - name: Ensure required packages are installed
      apt:
        pkg:
          - git
          - ufw
          - aptitude
        state: latest
        update_cache: yes

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
